src/java/com/stageo/model/Critere.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stageo.model;

import java.util.UUID;

/**
 *
 * @author admin
 */
public class Critere {
    private String IdCritere,
                   Nom;
    
    public Critere() {}

    public Critere(String IdCritere, String Nom) {
        this.IdCritere = IdCritere;
        this.Nom = Nom;
    }

    public Critere(String Nom) {
        String uniqueID = UUID.randomUUID().toString();
        this.IdCritere = uniqueID;
        this.Nom = Nom;
    }

    public String getIdCritere() {
        return IdCritere;
    }

    public void setIdCritere(String IdCritere) {
        this.IdCritere = IdCritere;
    }

    public String getNom() {
        return Nom;
    }

    public void setNom(String Nom) {
        this.Nom = Nom;
    }
    
    
    
}

web/WEB-INF/vue/liste-entreprises-coordonnateur.jsp
<!DOCTYPE html>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page import="java.sql.Connection"%>
<%@page import="java.util.List"%>
<%@page import="com.stageo.jdbc.Connexion"%>
<%@page import="com.stageo.jdbc.Config"%>
<%@page import="com.stageo.model.*"%>

<jsp:useBean id="connexion" class="com.stageo.jdbc.Connexion"></jsp:useBean>
<jsp:useBean id="udao" class="com.stageo.dao.UtilisateurDAO">
    <jsp:setProperty name="udao" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>
<jsp:useBean id="daoCompagnie" scope="page" class="com.stageo.dao.CompagnieDAO">
    <jsp:setProperty name="daoCompagnie" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>
<jsp:useBean id="daoOffreStage" scope="page" class="com.stageo.dao.StageDAO">
    <jsp:setProperty name="daoOffreStage" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>
<jsp:useBean id="daoAdresse" scope="page" class="com.stageo.dao.AdresseDAO">
    <jsp:setProperty name="daoAdresse" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>
<jsp:useBean id="daoEmployeur" scope="page" class="com.stageo.dao.EmployeurDAO">
    <jsp:setProperty name="daoEmployeur" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>

<c:set  var="listeCompagnie" value="${daoCompagnie.findAll()}"/>
<c:set var="listeEmployeurs" value="${daoEmployeur.findAll()}"></c:set>
<c:set var="listeOffres" value="${daoOffreStage.findByIdEmployeur(sessionScope.connecte)}"/>

<jsp:include page="/WEB-INF/vue/modals/modalDetailsEmployeurs.jsp"></jsp:include>

<section class='container py-5'>
    <article class='row'>
        <div class='col-12 col-lg-6'>
            <h1>Rechercher Compagnies</h1>
        </div>
        <div class='col-12 col-lg-6'>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text"><i class="fas fa-search"></i></label>
                </div>
                <input id="inputRecherche" onkeyup= "rechercherEntreprise()" type="text" class="form-control" placeholder="Recherche par mot-clef...">
            </div>
        </div>
    </article>
    
    <article class='row'>
        <table id="table" class="table table-hover">
            <thead>
                <tr>
                    <th onclick="sortTable(0, 'table')">Nom</th>
                    <th onclick="sortTable(1, 'table')">Contact</th>
                    <th onclick="sortTable(2, 'table')">Site Web</th>
                </tr>
            </thead>
            <tbody>
                <c:forEach items="${listeEmployeurs}" var="employeur">
                    <c:set var="user" value="${udao.read(employeur.idUtilisateur)}"></c:set>
                    <c:set var="compagnie" value="${daoCompagnie.read(employeur.compagnie.idCompagnie)}"></c:set>
                    <c:set var="adresse" value="${daoAdresse.read(compagnie.adresse.idAdresse)}"></c:set>
                        <tr>
                            <td>${compagnie.nom}</td>
                            <td>${user.nom} ${user.prenom}</td>
                            <td>${compagnie.pageWeb}</td>
                            
                            <td hidden>${user.nom}</td>
                            <td hidden>${user.prenom}</td>
                            <td hidden>${user.email}</td>
                            <td hidden>${user.telephone}</td>
                            
                            <td hidden>${employeur.fonction}</td>
                            <td hidden>${compagnie.nom}</td>
                            <td hidden>${compagnie.secteur}</td>
                            <td hidden>${compagnie.pageWeb}</td>
                            <td hidden>${compagnie.telEntreprise}</td>
                            <td hidden>${compagnie.lienGoogleMaps}</td>
                            <td hidden>${compagnie.taille}</td>
                            <td hidden>${compagnie.kilometrage}</td>
                            <td hidden>${compagnie.nbEmployes}</td>
                            
                            <td hidden>${adresse.adresseLigne1}</td>
                            <td hidden>${adresse.adresseLigne2}</td>
                            <td hidden>${adresse.ville}</td>
                            <td hidden>${adresse.codePostal}</td>
                            <td hidden>${adresse.province}</td>
                            <td hidden>${adresse.pays}</td>
                        </tr>
                </c:forEach>
            </tbody>
        </table>
    </article>
</section>

<!--ANCIEN CODE-->
<!--<div class="container" >
    <div class="row" >
        <div class="col-md-7">
            <div class="card">
                <div class="card-header titreProfil2">
                    <h1 class="card-title ">Rechercher Compagnies</h1>
                </div>
                 Section de recherche des compagnies 
                 Barre de recherche 
                <div class="card-body">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text"><i class="fas fa-search"></i></label>
                        </div>
                        <input id="inputRecherche" type="text" class="form-control" placeholder="Recherche par mot-clef...">
                    </div>
                     Fin de la barre de recherche 

                    <div class="">
                        <table id="table" class="table table-hover borderTable">
                            <thead>
                                <tr>
                                    <th>Nom <a href="#" class="fa fa-arrows-alt-v"></a></th>
                                    <th>Site Web <a href="#" class="fa fa-arrows-alt-v"></a></th>
                                </tr>
                            </thead>
                            <tbody>
                                <c:forEach items="${listeCompagnie}" var="compagnie">
                                        <tr>
                                            <td>${compagnie.nom}</td>
                                            <td>${compagnie.pageWeb}</td>
                                        </tr>
                                </c:forEach>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>-->
        <!-- Fin de la section de recherche des stages -->
        
<!-- Fin footer -->
<script>
    var nbComp = 0;

    var table = document.getElementById('table');

    for (var i = 1; i < table.rows.length; i++)
    {
        table.rows[i].onclick = function ()
        {
            
            //rIndex = this.rowIndex;
            document.getElementById("prenom").value = this.cells[4].innerHTML;
            document.getElementById("nom").value = this.cells[3].innerHTML;
            document.getElementById("email").value = this.cells[5].innerHTML;
            document.getElementById("tel").value = this.cells[6].innerHTML;
            document.getElementById("fonction").value = this.cells[7].innerHTML; 
            document.getElementById("nomEntreprise").value = this.cells[8].innerHTML; 
            document.getElementById("secteur").value = this.cells[9].innerHTML; 
            document.getElementById("pageWeb").value = this.cells[10].innerHTML; 
            document.getElementById("telEntreprise").value = this.cells[11].innerHTML; 
            document.getElementById("lienGoogleMaps").value = this.cells[12].innerHTML; 
            document.getElementById("taille").value = this.cells[13].innerHTML; 
            document.getElementById("kilometrage").value = this.cells[14].innerHTML; 
            document.getElementById("nbEmployes").value = this.cells[15].innerHTML; 
            document.getElementById("adresseLigne1").value = this.cells[16].innerHTML; 
            document.getElementById("adresseLigne2").value = this.cells[17].innerHTML;
            document.getElementById("ville").value = this.cells[18].innerHTML;
            document.getElementById("codePostal").value = this.cells[19].innerHTML;
            document.getElementById("province").value = this.cells[20].innerHTML;
            document.getElementById("pays").value = this.cells[21].innerHTML;
//            $('#' + this.cells[4].innerHTML).children("td[name='crit']").each(function (index) {
//                document.getElementById("criteresStageContent").innerHTML += "<h2 class='Catpill'><span class='badge badge-pill mb-1'>" + $(this).text() + "</span></h2>";
//            });
            $(".Catpill").addClass("blue")
                    .css({"display": "inline"});
            
            $('#modalDetailsEmployeurs').modal('show');
        };
    }
    
    function rechercherEntreprise() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("inputRecherche");
    filter = input.value.toUpperCase();
    table = document.getElementById("table");
    tr = table.getElementsByTagName("tr");

    for (i = 1; i < tr.length; i++) {
        var td0 = tr[i].getElementsByTagName("td")[0].innerHTML.toUpperCase();
        var td1 = tr[i].getElementsByTagName("td")[1].textContent.toUpperCase();
        var td2 = tr[i].getElementsByTagName("td")[2].textContent.toUpperCase();
        if (td0.indexOf(filter) > -1 || td1.indexOf(filter) > -1 || td2.indexOf(filter) > -1 ) {
            tr[i].style.display = "";
        } else {
            tr[i].style.display = "none";
        }      
    }
    }
    
    function sortTableActif(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("table");
  switching = true;
  dir = "asc"; 

  while (switching) {
    switching = false;
    rows = table.rows;

    for (i = 1; i < (rows.length - 1); i++) {

      shouldSwitch = false;

      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          shouldSwitch= true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {

      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      switchcount ++;      
    } else {

      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}


</script>

<style>
    th{
        cursor:pointer;
    }
</style>
        

web/WEB-INF/vue/liste-stagiaires-coordonnateur.jsp
<!DOCTYPE html>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page import="java.sql.Connection"%>
<%@page import="java.util.List"%>
<%@page import="com.stageo.jdbc.Connexion"%>
<%@page import="com.stageo.jdbc.Config"%>
<%@page import="com.stageo.model.*"%>
<%@page import="com.util.Util"%>

<jsp:useBean id="connexion" class="com.stageo.jdbc.Connexion"></jsp:useBean>
<jsp:useBean id="dao" class="com.stageo.dao.UtilisateurDAO">
    <jsp:setProperty name="dao" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>
<c:set var="listeUser" value="${dao.findAll()}"/>
<jsp:useBean id="daoCritere" scope="page" class="com.stageo.dao.CritereDAO">
    <jsp:setProperty name="daoCritere" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>
<jsp:useBean id="edao" class="com.stageo.dao.EtudiantDAO">
    <jsp:setProperty name="edao" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>

<c:set  var="listeCriteres" value="${daoCritere.findAll()}"/>

<jsp:include page="/WEB-INF/vue/modals/modalDetailsEtudiants.jsp"></jsp:include>
<jsp:include page="/WEB-INF/vue/modals/modalDetailsOffres.jsp"></jsp:include>

<section class="container py-5">
    <article class="row">
        <div class="col-12 col-lg-6">
            <h1>Rechercher Stagiaire</h1>
        </div>
        <div class="col-12 col-lg-6">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text"><i class="fas fa-search"></i></label>
                </div>
                <input id="inputRecherche" onkeyup="rechercherEtudiant()" type="text" class="form-control" placeholder="Recherche par mot-clef...">
            </div>
        </div>
    </article>
    
    <article class="row">
        <div class="col-12">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text">
                        <button class="btn my-btn-outline-secondary dropdown-toggle main-input" type="button" data-toggle="dropdown"> Filtrer par Compétences <span class="caret"></span></button>
                        <ul class="dropdown-menu" id="liste">
                            <c:forEach items="${listeCriteres}" varStatus="loop" var="critereRecherche">
                                <li class="elementCritere"name="${critereRecherche.nom}">${critereRecherche.nom}
                                </li>
                            </c:forEach>    
                        </ul>
                    </label>
                </div>
                <!-- Conteneur de comperence -->
                <div class="col-sm-8" >
                    <div id="conteneurCompetences">

                    </div>
                </div>
            </div>
        </div>
    </article>
    
    <article class="row">
        <div class="col-12">
            <table id="table" class="table table-hover">
                <thead>
                    <tr>
                        <th onclick="sortTable(0, 'table')">Nom <span class="glyphicon glyphicon-sort-by-alphabet"></span></a></th>
                        <th onclick="sortTable(1, 'table')">Prénom <span class="glyphicon glyphicon-sort-by-alphabet"></span></a></th>
                        <th onclick="sortTable(2, 'table')">Courriel <span class="glyphicon glyphicon-sort-by-alphabet"></span></a></th>
                    </tr>
                </thead>
                <tbody>
                    <c:forEach items="${listeUser}" var="user">
                        <c:if test = "${user.role == 'etudiant'}">
                            <c:set var="etudiant" value="${edao.read(user.idUtilisateur)}"></c:set>
                                <tr>
                                    <td>${user.nom}</td>
                                    <td>${user.prenom}</td>
                                    <td>${user.email}</td>
                                    <td hidden>${user.idUtilisateur}</td>
                                    <td hidden>${user.telephone}</td>
                                    <td hidden>${Util.toUTF8(etudiant.ville)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.profilEtudes)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.stageSession)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.anglaisEcrit)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.anglaisParle)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.permisConduire)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.demarcheEnCours)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.login365)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.numeroDA)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.moyenTransport)}</td>
                                    <td hidden>${Util.toUTF8(etudiant.preferences)}</td>
                                    
                                    <td hidden name="crit">
                                        <c:forEach  items="${etudiant.listeCritere}" var="crit">
                                            ${crit.nom},
                                        </c:forEach>
                                    </td>
                                        
                                    
                                </tr>
                        </c:if>
                    </c:forEach>
                </tbody>
            </table>
        </div>
    </article>
</section>

<script>
    var nbComp = 0;

    var table = document.getElementById('table');
    var listeCriteres;

    for (var i = 1; i < table.rows.length; i++)
    {
        table.rows[i].onclick = function ()
        {
            
            //rIndex = this.rowIndex;
            document.getElementById("prenom").value = this.cells[1].innerHTML;
            document.getElementById("nom").value = this.cells[0].innerHTML;
            document.getElementById("email").value = this.cells[2].innerHTML;
            document.getElementById("idUser").value = this.cells[3].innerHTML;
            document.getElementById("tel").value = this.cells[4].innerHTML;
            document.getElementById("ville").value = this.cells[5].innerHTML;
            document.getElementById("profilEtudes").value = this.cells[6].innerHTML;
            document.getElementById("stageSession").value = this.cells[7].innerHTML;
            document.getElementById("anglaisEcrit").value = this.cells[8].innerHTML;
            document.getElementById("anglaisParle").value = this.cells[9].innerHTML;
            document.getElementById("permisConduire").value = this.cells[10].innerHTML;
            document.getElementById("demarcheEnCours").value = this.cells[11].innerHTML;
            document.getElementById("login365").value = this.cells[12].innerHTML;
            document.getElementById("numeroDA").value = this.cells[13].innerHTML;
            document.getElementById("moyenTransport").value = this.cells[14].innerHTML;
            document.getElementById("preferences").innerHTML = this.cells[15].innerHTML;
            
            listeCriteres = this.cells[16].innerHTML;
            listeCriteres = listeCriteres.trim();
            listeCriteres = listeCriteres.split(",");
            console.log(listeCriteres);
            document.getElementById("criteresStageContent").innerHTML = "";
            for (var i = 0; i < listeCriteres.length; i++){
                document.getElementById("criteresStageContent").innerHTML += "<h2 class='Catpill'><span class='badge badge-pill mb-1'>" + listeCriteres[i] + "</span></h2>";
            }
            
//            $('#' + this.cells[4].innerHTML).children("td[name='crit']").each(function (index) {
//                document.getElementById("criteresStageContent").innerHTML += "<h2 class='Catpill'><span class='badge badge-pill mb-1'>" + $(this).text() + "</span></h2>";
//            });
            $(".Catpill").css({"display": "inline"});
            
            $('#modalDetailsEtudiants').modal('show');

        };
    }
    
    $(document).ready(function () {
        $(".elementCritere").click(function (event) {
            document.getElementById("conteneurCompetences").innerHTML += "<span class='competence badge badge-primary'  onclick='enleverCompetence(" + nbComp + ")' id='competence" + nbComp + "'>" + event.target.innerHTML + " <a class='fas fa-times' ></a></span>";
            $(".competence").addClass("alert alert-info ")
                    .css("margin", "2%");
            nbComp++;
        });

    });

    function rechercherEtudiant() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("inputRecherche");
    filter = input.value.toUpperCase();
    table = document.getElementById("table");
    tr = table.getElementsByTagName("tr");
    
    for (i = 1; i < tr.length; i++) {
        var td0 = tr[i].getElementsByTagName("td")[0].textContent.toUpperCase();
        var td1 = tr[i].getElementsByTagName("td")[1].textContent.toUpperCase();
        var td2 = tr[i].getElementsByTagName("td")[2].textContent.toUpperCase();
        if (td0.indexOf(filter) > -1 || td1.indexOf(filter) > -1 || td2.indexOf(filter) > -1 ) {
            tr[i].style.display = "";
        } else {
            tr[i].style.display = "none";
        }      
    }
    }
    
</script>

<style>
    th{
        cursor:pointer;
    }
</style>    

web/WEB-INF/vue/profil-administrateur.jsp
<%-- 
    Document   : profilEtudiant
    Created on : 2018-10-25, 10:17:32
    Author     : JP
--%>
<%@page import="java.sql.Connection"%>
<%@page import="java.util.List"%>
<%@page import="com.stageo.jdbc.Connexion"%>
<%@page import="com.stageo.jdbc.Config"%>
<%@page import="com.stageo.model.Utilisateur"%>
<%@page import="com.stageo.dao.UtilisateurDAO"%>
<%@page import="com.util.Util"%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<!DOCTYPE html>

<jsp:useBean id="connexion" class="com.stageo.jdbc.Connexion"></jsp:useBean>
<jsp:useBean id="daoCritere" scope="page" class="com.stageo.dao.CritereDAO">
    <jsp:setProperty name="daoCritere" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>
<jsp:useBean id="dao" class="com.stageo.dao.UtilisateurDAO">
    <jsp:setProperty name="dao" property="cnx" value="${connexion.connection}"></jsp:setProperty>
</jsp:useBean>
<c:set var="listeCriteres" value="${daoCritere.findAll()}"/>
<c:set var="admin" scope="page" value="${dao.read(sessionScope.connecte)}"/>

<div class="jumbotron jumbotron-fluid stylish-color white-text">
    <section class="container">
        <article class="row justify-content-center">
            <div class="col-lg-6 col-12 text-center">
                <h1><i class="fas fa-user-circle" style="font-size:150px"></i></h1>
                <h3>${Util.toUTF8(admin.prenom)} ${Util.toUTF8(admin.nom)}</h3>
                <h4>@${admin.nomUtilisateur}</h4>
                <h5>${admin.email}</h5>
                <h5>${fn:toUpperCase(admin.role)}</h5>

                <a data-toggle="modal" href="#monModalMotDePasse" class="btn btn-success btn-sm" role="button">Changer mon mot de passe</a>
                <a data-toggle="modal" href="#monModalNomUtilisateur" class="btn btn-success btn-sm" role="button">Changer mon nom d'utilisateur</a>
            </div>
        </article>
    </section>
</div>
                
<section class="container">
    <form action="*.do" method="post">
        <article class="row border border-dark border-right-0 border-bottom-0 border-left-0 py-5">
            <div class="col-12 col-lg-6">
                <h1><strong>Informations générales</strong></h1>
            </div>

            <div class="col-12 col-lg-6">
                <section class="container-fluid p-0">
                    <article class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="">Nom</label>
                                <input type="text" class="form-control" name="nom" value="${Util.toUTF8(admin.nom)}">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="">Prénom</label>
                                <input type="text" class="form-control" name="prenom" value="${Util.toUTF8(admin.prenom)}">
                            </div>
                        </div>
                    </article>
                </section>
                
                <div class="form-group">
                    <label for="">Adresse courriel</label>
                    <label i class="fas fa-question-circle" for="" data-toggle="tooltip" data-placement="right" title="Format : abcd@nom-de-domaine.com"></label>
                    <input type="email" class="form-control" name="email" value="${admin.email}">
                </div>
                <div class="form-group">
                    <label for="">Numéro de téléphone</label>
                    <label i class="fas fa-question-circle" for="" data-toggle="tooltip" data-placement="right" title="Format : XXX-XXX-XXXX"></label>
                    <input type="tel" class="form-control" name="tel" value="${admin.telephone}" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}">
                </div>
                
            </div>
        </article>
        <article class="row border border-dark border-right-0 border-bottom-0 border-left-0 py-5">
            <div class="col-12 col-lg-6">
                
            </div>
            
            <div class="col-12 col-lg-6 d-flex justify-content-between">
                <button type="submit" class="btn btn-success" name="tache" value="effectuerModificationUtilisateur">
                    Enregistrer les modifications
                </button>
                <button type="submit" class="btn btn-light" name="tache" value="afficherPageProfil">Annuler</button>
            </div>
            
        </article>
    </form>
</section>

<div class="container">
    <div class="row">
        <div class="col-12  mx-auto">
            <div class="card">
                <div class="card-header">
                    <div class="card-title titreProfil">
                        <h1>Espace coordonnateur</h1>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card-subtitle mb-3"><h4>Gestion des compétences:</h4>
                    </div>


                    <form action="*.do?tache=ajoutCritere" method = "post" >
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <label class="input-group-text">Nouvelle Compétence</label>
                                </div>
                                <input type="text"  name="critere" class="form-control" id="critere"  placeholder="Critère">
                                <button type="submit" class="btn my-btn-outline-primary my-2 my-sm-0"> Ajouter</button>
                            </div>

                    </form>
                    <div class="table-responsive">

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <td >Critères <a href="#" class="fa fa-arrows-alt-v my-btn-outline-secondary"></a></td>
                                    <td>Étudiants <a href="#" class="fa fa-arrows-alt-v my-btn-outline-secondary"></a></td>
                                    <td>Requises <a href="#" class="fa fa-arrows-alt-v my-btn-outline-secondary"></a></td>
                                    <td>Supprimer <a href="#" class="fa fa-arrows-alt-v my-btn-outline-secondary"></a></td>
                                </tr>
                            </thead>
                            <tbody>
                                <c:forEach items="${listeCriteres}" var="critere"> 
                                    <tr>
                                        <td>${critere.nom}</td>
                                        <td>4</td>
                                        <td>4</td>
                                        <td>
                                            <form action="*.do?tache=supprimerCritere" method = "post">

                                                <input type="hidden" value="${critere.idCritere}" name="suppressionCrit" class="form-control" id="suppressionCrit">
                                                <button type="submit" class="my-btn-outline-primary"><a><i class="fas fa-trash-alt"></i></a></button>
                                            </form>
                                        </td>
                                    </tr>
                                </c:forEach> 

                            </tbody>
                        </table>
                    </div>
                </div>    
            </div> 
        </div>
    </div>
    
    <div class="row">
        <div class="col-12 mx-auto my-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title titreProfil">
                        <h1>Espace administrateur</h1>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card-subtitle mb-3">
                        <h4>Ouverture de compte</h4>
                    </div>
                    
                    <div class="card-text">
                        <form action="*.do?tache=afficherPageInscription" method="post">
                            <button type="submit" class='btn btn-info'>Créer un compte</button>
                        </form>
                    </div>
                </div>    
            </div> 
        </div>
    </div>
</div>